# File: docker-compose.yml

services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ejemplo123

  api:
    build: ./api
    container_name: api
    ports:
      - "3000:3000"
    depends_on:
      - mongodb    
    env_file:
      - ./api/.env
    restart: unless-stopped

volumes:
  mongodb_data: